config/routes.rb
Rails.application.routes.draw do

  resources :playlists

  resources :profiles

  resources :songs do
    resources :comments
  end

  devise_for :users do
    get 'sign_in', to: "devise/sessions#new"
    
    get 'sign_up', to: "devise/registrations#new"
  end
  
  root to: "home#index" 

  get '/profile', to: 'profile#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  acts_as_commentable
  
  has_and_belongs_to_many :users
  has_and_belongs_to_many :songs
  has_many :comments

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  mount_uploader :profile_image, ProfileImageUploader
  
  belongs_to :user

end

app/models/song.rb
class Song < ActiveRecord::Base  
  mount_uploader :song_image, SongImageUploader
  mount_uploader :song_audio, SongAudioUploader

  acts_as_commentable

  has_and_belongs_to_many :playlists  
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  has_many :songs
  has_many :comments
  has_and_belongs_to_many :playlists
  has_one :profile
  before_create :build_profile #creates profile at user registration


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    # def after_sign_in_path_for(profiles)
    #   edit_profile_path(profiles)
    # end

    # def after_sign_up_path_for(profiles)
    #   profile_path(profiles)
    # end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create
     @song = Song.find(params[:song_id])
     @comment = @song.comments.new(comment_params)
     @comment.user = current_user
     @comment.save
     redirect_to @song
   end     

    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @playlists = Playlist.all
    respond_with(@playlists)
  end

  def show
    respond_with(@playlist)
  end

  def new
    @playlist = Playlist.new
    respond_with(@playlist)
  end

  def edit
  end

  def create
    @playlist = Playlist.new(playlist_params)
    # @song = current_user.songs.new(song_params)
    
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end 
  end

  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully deleted.' }
      format.json { head :no_content }
    end
    
  end

  private
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    def playlist_params
      params.require(:playlist).permit(:name, { song_ids: []})
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]


  def index
    @profiles = Profile.all
  end

    def show
    end

    def new
      @profile = Profile.new
    end

    def create
      @profile = Profile.new(profile_params)
      # @song = current_user.songs.new(song_params)
      
      respond_to do |format|
        if @profile.save
          format.html { redirect_to @profile }
          format.json { render :show, status: :created, location: @profile }
        else
          format.html { render :new }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @profile.update(profile_params)
          format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @profile }
        else
          format.html { render :edit }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end 
    end

    def destroy
      @profile.destroy
      respond_to do |format|
        format.html { redirect_to profiles_url, notice: 'Profile was successfully deleted.' }
        format.json { head :no_content }
      end
    end

    private
      def set_profile
        @profile = Profile.find(params[:id])
      end

      def profile_params
        params.require(:profile).permit(:name, :profile_image, :bio)
      end
  end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @songs = Song.all
    respond_with(@songs)
  end

  def show
    respond_with(@song)
  end

  def new
    @song = Song.new
    respond_with(@song)
  end

  def edit
  end

  def create
    @song = Song.new(song_params)
    # @song = current_user.songs.new(song_params)
    
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end 
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :song_image, :remote_song_image_url, :song_audio, :user_id, { playlist_ids: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/comments/_form.html.erb
<div>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "The Music Network" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <nav class="top-bar row" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "The Music Network", root_path %></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">            

            <% if current_user %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>                       
            
            <li class="has-dropdown">
              <a href="#">Join us</a>
              <ul class="dropdown">
                <li><%= link_to "Sign in", new_user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
              </ul>
            </li>
          </ul>
          <% end %>

          <!-- Left Nav Section -->
          <ul class="left">
            <li><%= link_to "Songs", songs_path %></li>
            <li><%= link_to "Playlists", playlists_path %></li>            
            <li><%= link_to "Profiles", profiles_path %></li>

          </ul>
        </section>
      </nav>
    </header>

    <% if params[:controller] == "home" && params[:action] == "index" %>
      <section class="fullwidth-image">
        <h1>LDN. NOT NYC</h1>
        <h4>The hip hop music network for London</h4>          
      </section>
      <div class="fullwidth-button"><%= link_to "Browse songs", songs_path %></div>



    <% end %>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="row">
      <%= yield %>
    </main>
    <footer></footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

   <div class="field">
     <%= f.collection_check_boxes :song_ids, Song.all, :id, :name do |b| %>
       <%= b.check_box + b.label { b.text } %><br>
     <% end %>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %>
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Your playlists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= link_to 'New Playlist', new_playlist_path %>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Delete', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p>
  <strong>Songs in this playlists:</strong><br>
  <% @playlist.songs.each do |song| %>
    <%= song.name %><br> 
  <% end %>
</p>


<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 
  <div class="field">
    <%= f.label :profile_image %><br>
    <%= f.file_field :profile_image %>
  </div>

  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %>
<%= link_to 'Back', profile_path %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= link_to 'New Profile', new_profile_path %>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= image_tag profile.profile_image.url, size: "100" %></td>
        <td><%= link_to profile.name, profile_path(profile) %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Delete', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<%= image_tag @profile.profile_image.url %></p>

<strong>Biographical information:</strong>

<p> <%= @profile.bio %> </p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :song_audio %><br>
    <%= f.file_field :song_audio %>
  </div>

  <div class="field">
    <%= f.label :song_image %><br>
    <%= f.file_field :song_image %>
  </div>
 
  <div>
      <%= f.label :remote_song_image_url %>
      <%= f.text_field :remote_song_image_url %>
  </div>

   <div class="field">
     <%= f.collection_check_boxes :playlist_ids, Playlist.all, :id, :name do |b| %>
       <%= b.check_box + b.label { b.text } %><br>
     <% end %>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Your songs</h1>

<table>
  <thead>
    <tr>
      <th>Art</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= link_to 'New Song', new_song_path %>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= image_tag song.song_image.url, size: "100" %></td>
        <td><%= song.name %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

  <p><strong>Audio:</strong>
  <%= audio_tag @song.song_audio.url, autoplay: false, controls: true %>
  </p>

  <p><strong>Image:</strong></p>
  <%= image_tag @song.song_image.url %></p>

  <strong>Song appears in these playlists:</strong><br>
  <% @song.playlists.each do |playlist| %>
    <%= playlist.name %><br>
  <% end %>


<%= form_for [@song, @song.comments.new] do |f| %>
  <%= render partial: 'comments/form', locals: { f: f } %>
  <%= f.submit 'Add Comment!' %>
  <% end %>

<% @song.comments.each do |comment| %>
  <%= comment.comment %>
  <br>
  <p>Posted by: <%= comment.user.try :name %></p>
  <hr>
  <% end %>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>